In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('nyc.csv')

In [ ]:
#removing duplicate
df=df.drop_duplicates()
df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,19-10-2018,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,21-05-2019,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,05-07-2019,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,19-11-2018,0.10,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48890,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,70,2,0,NaN,NaN,2,9
48891,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317,Private room,40,4,0,NaN,NaN,2,36
48892,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,115,10,0,NaN,NaN,1,27
48893,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,55,1,0,NaN,NaN,6,2
48894,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,90,7,0,NaN,NaN,1,23

In [ ]:
#deleting columns that would be irrelevant for analysis
df=df.drop(['name','neighbourhood','calculated_host_listings_count'],axis=1)
df.head()

,id,host_id,host_name,neighbourhood_group,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,availability_365
0,2539,2787,John,Brooklyn,40.64749,-73.97237,Private room,149,1,9,19-10-2018,0.21,365
1,2595,2845,Jennifer,Manhattan,40.75362,-73.98377,Entire home/apt,225,1,45,21-05-2019,0.38,355
2,3647,4632,Elisabeth,Manhattan,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,365
3,3831,4869,LisaRoxanne,Brooklyn,40.68514,-73.95976,Entire home/apt,89,1,270,05-07-2019,4.64,194
4,5022,7192,Laura,Manhattan,40.79851,-73.94399,Entire home/apt,80,10,9,19-11-2018,0.10,0

In [ ]:
#removing duplicates
df=df.drop_duplicates()
df

,id,host_id,host_name,neighbourhood_group,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,availability_365
0,2539,2787,John,Brooklyn,40.64749,-73.97237,Private room,149,1,9,19-10-2018,0.21,365
1,2595,2845,Jennifer,Manhattan,40.75362,-73.98377,Entire home/apt,225,1,45,21-05-2019,0.38,355
2,3647,4632,Elisabeth,Manhattan,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,365
3,3831,4869,LisaRoxanne,Brooklyn,40.68514,-73.95976,Entire home/apt,89,1,270,05-07-2019,4.64,194
4,5022,7192,Laura,Manhattan,40.79851,-73.94399,Entire home/apt,80,10,9,19-11-2018,0.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48890,36484665,8232441,Sabrina,Brooklyn,40.67853,-73.94995,Private room,70,2,0,NaN,NaN,9
48891,36485057,6570630,Marisol,Brooklyn,40.70184,-73.93317,Private room,40,4,0,NaN,NaN,36
48892,36485431,23492952,Ilgar & Aysel,Manhattan,40.81475,-73.94867,Entire home/apt,115,10,0,NaN,NaN,27
48893,36485609,30985759,Taz,Manhattan,40.75751,-73.99112,Shared room,55,1,0,NaN,NaN,2
48894,36487245,68119814,Christophe,Manhattan,40.76404,-73.98933,Private room,90,7,0,NaN,NaN,23

In [ ]:
#checking for null values,dtype in all columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   48895 non-null  int64
 1   host_id              48895 non-null  int64
 2   host_name            48874 non-null  object
 3   neighbourhood_group  48895 non-null  object
 4   latitude             48895 non-null  float64
 5   longitude            48895 non-null  float64
 6   room_type            48895 non-null  object
 7   price                48895 non-null  int64
 8   minimum_nights       48895 non-null  int64
 9   number_of_reviews    48895 non-null  int64
 10  last_review          38843 non-null  object
 11  reviews_per_month    38843 non-null  float64
 12  availability_365     48895 non-null  int64
dtypes: float64(3), int64(6), object(4)
memory usage: 4.8+ MB

In [ ]:
#converting dtype and removing nan values
df['host_name']=df['host_name'].astype('string')
df['host_name']=df['host_name'].str.replace("nan"," ")

#ewmoving  non alphabetical character
df['host_name']=df['host_name'].str.replace(r'[^a-zA-Z\s]','',regex=True)
df

#creating space between 2 names
df['host_name'] = df['host_name'].str.replace(r'(\w)([A-Z])', r'\1 \2', regex=True)
df

,id,host_id,host_name,neighbourhood_group,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,availability_365
0,2539,2787,John,Brooklyn,40.64749,-73.97237,Private room,149,1,9,19-10-2018,0.21,365
1,2595,2845,Jennifer,Manhattan,40.75362,-73.98377,Entire home/apt,225,1,45,21-05-2019,0.38,355
2,3647,4632,Elisabeth,Manhattan,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,365
3,3831,4869,Lisa Roxanne,Brooklyn,40.68514,-73.95976,Entire home/apt,89,1,270,05-07-2019,4.64,194
4,5022,7192,Laura,Manhattan,40.79851,-73.94399,Entire home/apt,80,10,9,19-11-2018,0.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48890,36484665,8232441,Sabrina,Brooklyn,40.67853,-73.94995,Private room,70,2,0,NaN,NaN,9
48891,36485057,6570630,Marisol,Brooklyn,40.70184,-73.93317,Private room,40,4,0,NaN,NaN,36
48892,36485431,23492952,Ilgar Aysel,Manhattan,40.81475,-73.94867,Entire home/apt,115,10,0,NaN,NaN,27
48893,36485609,30985759,Taz,Manhattan,40.75751,-73.99112,Shared room,55,1,0,NaN,NaN,2
48894,36487245,68119814,Christophe,Manhattan,40.76404,-73.98933,Private room,90,7,0,NaN,NaN,23

In [ ]:
#obtaining data where Airbnb is priced
df=df[df['price']!=0]
df.head()

,id,host_id,host_name,neighbourhood_group,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,availability_365
0,2539,2787,John,Brooklyn,40.64749,-73.97237,Private room,149,1,9,19-10-2018,0.21,365
1,2595,2845,Jennifer,Manhattan,40.75362,-73.98377,Entire home/apt,225,1,45,21-05-2019,0.38,355
2,3647,4632,Elisabeth,Manhattan,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,365
3,3831,4869,Lisa Roxanne,Brooklyn,40.68514,-73.95976,Entire home/apt,89,1,270,05-07-2019,4.64,194
4,5022,7192,Laura,Manhattan,40.79851,-73.94399,Entire home/apt,80,10,9,19-11-2018,0.10,0

In [ ]:
#if we need data for minimum nights in a year or less
df=df[df['minimum_nights']<=365]
df

,id,host_id,host_name,neighbourhood_group,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,availability_365
0,2539,2787,John,Brooklyn,40.64749,-73.97237,Private room,149,1,9,19-10-2018,0.21,365
1,2595,2845,Jennifer,Manhattan,40.75362,-73.98377,Entire home/apt,225,1,45,21-05-2019,0.38,355
2,3647,4632,Elisabeth,Manhattan,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,365
3,3831,4869,Lisa Roxanne,Brooklyn,40.68514,-73.95976,Entire home/apt,89,1,270,05-07-2019,4.64,194
4,5022,7192,Laura,Manhattan,40.79851,-73.94399,Entire home/apt,80,10,9,19-11-2018,0.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48890,36484665,8232441,Sabrina,Brooklyn,40.67853,-73.94995,Private room,70,2,0,NaN,NaN,9
48891,36485057,6570630,Marisol,Brooklyn,40.70184,-73.93317,Private room,40,4,0,NaN,NaN,36
48892,36485431,23492952,Ilgar Aysel,Manhattan,40.81475,-73.94867,Entire home/apt,115,10,0,NaN,NaN,27
48893,36485609,30985759,Taz,Manhattan,40.75751,-73.99112,Shared room,55,1,0,NaN,NaN,2
48894,36487245,68119814,Christophe,Manhattan,40.76404,-73.98933,Private room,90,7,0,NaN,NaN,23

In [ ]:
#data where availability is atleast 1 day
df=df[df['availability_365']!=0]
df

,id,host_id,host_name,neighbourhood_group,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,availability_365
0,2539,2787,John,Brooklyn,40.64749,-73.97237,Private room,149,1,9,19-10-2018,0.21,365
1,2595,2845,Jennifer,Manhattan,40.75362,-73.98377,Entire home/apt,225,1,45,21-05-2019,0.38,355
2,3647,4632,Elisabeth,Manhattan,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,365
3,3831,4869,Lisa Roxanne,Brooklyn,40.68514,-73.95976,Entire home/apt,89,1,270,05-07-2019,4.64,194
5,5099,7322,Chris,Manhattan,40.74767,-73.97500,Entire home/apt,200,3,74,22-06-2019,0.59,129
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48890,36484665,8232441,Sabrina,Brooklyn,40.67853,-73.94995,Private room,70,2,0,NaN,NaN,9
48891,36485057,6570630,Marisol,Brooklyn,40.70184,-73.93317,Private room,40,4,0,NaN,NaN,36
48892,36485431,23492952,Ilgar Aysel,Manhattan,40.81475,-73.94867,Entire home/apt,115,10,0,NaN,NaN,27
48893,36485609,30985759,Taz,Manhattan,40.75751,-73.99112,Shared room,55,1,0,NaN,NaN,2
48894,36487245,68119814,Christophe,Manhattan,40.76404,-73.98933,Private room,90,7,0,NaN,NaN,23

In [ ]:
#converting data type to string
df['neighbourhood_group']=df['neighbourhood_group'].astype('string')
df['neighbourhood_group']

#deleting non values from
df['neighbourhood_group']=df['neighbourhood_group'].str.replace("nan"," ")
df

<ipython-input-15-5c7a1e015a93>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['neighbourhood_group']=df['neighbourhood_group'].astype('string')
<ipython-input-15-5c7a1e015a93>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['neighbourhood_group']=df['neighbourhood_group'].str.replace("nan"," ")

,id,host_id,host_name,neighbourhood_group,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,availability_365
0,2539,2787,John,Brooklyn,40.64749,-73.97237,Private room,149,1,9,19-10-2018,0.21,365
1,2595,2845,Jennifer,Manhattan,40.75362,-73.98377,Entire home/apt,225,1,45,21-05-2019,0.38,355
2,3647,4632,Elisabeth,Manhattan,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,365
3,3831,4869,Lisa Roxanne,Brooklyn,40.68514,-73.95976,Entire home/apt,89,1,270,05-07-2019,4.64,194
5,5099,7322,Chris,Manhattan,40.74767,-73.97500,Entire home/apt,200,3,74,22-06-2019,0.59,129
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48890,36484665,8232441,Sabrina,Brooklyn,40.67853,-73.94995,Private room,70,2,0,NaN,NaN,9
48891,36485057,6570630,Marisol,Brooklyn,40.70184,-73.93317,Private room,40,4,0,NaN,NaN,36
48892,36485431,23492952,Ilgar Aysel,Manhattan,40.81475,-73.94867,Entire home/apt,115,10,0,NaN,NaN,27
48893,36485609,30985759,Taz,Manhattan,40.75751,-73.99112,Shared room,55,1,0,NaN,NaN,2
48894,36487245,68119814,Christophe,Manhattan,40.76404,-73.98933,Private room,90,7,0,NaN,NaN,23

In [ ]:
#converting datatype to string
df['room_type']=df['room_type'].astype('string')
df['room_type']

#deleting non values
df['room_type']=df['room_type'].str.replace("nan"," ")
df

<ipython-input-17-2c226105f1e0>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['room_type']=df['room_type'].astype('string')
<ipython-input-17-2c226105f1e0>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['room_type']=df['room_type'].str.replace("nan"," ")

,id,host_id,host_name,neighbourhood_group,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,availability_365
0,2539,2787,John,Brooklyn,40.64749,-73.97237,Private room,149,1,9,19-10-2018,0.21,365
1,2595,2845,Jennifer,Manhattan,40.75362,-73.98377,Entire home/apt,225,1,45,21-05-2019,0.38,355
2,3647,4632,Elisabeth,Manhattan,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,365
3,3831,4869,Lisa Roxanne,Brooklyn,40.68514,-73.95976,Entire home/apt,89,1,270,05-07-2019,4.64,194
5,5099,7322,Chris,Manhattan,40.74767,-73.97500,Entire home/apt,200,3,74,22-06-2019,0.59,129
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48890,36484665,8232441,Sabrina,Brooklyn,40.67853,-73.94995,Private room,70,2,0,NaN,NaN,9
48891,36485057,6570630,Marisol,Brooklyn,40.70184,-73.93317,Private room,40,4,0,NaN,NaN,36
48892,36485431,23492952,Ilgar Aysel,Manhattan,40.81475,-73.94867,Entire home/apt,115,10,0,NaN,NaN,27
48893,36485609,30985759,Taz,Manhattan,40.75751,-73.99112,Shared room,55,1,0,NaN,NaN,2
48894,36487245,68119814,Christophe,Manhattan,40.76404,-73.98933,Private room,90,7,0,NaN,NaN,23